spring:
  application:
    name: forex-service
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url:  ${POSTGRESQL_URL:jdbc:postgresql://localhost:5432/forex}
    username: ${POSTGRESQL_USER:admin}
    password: ${POSTGRESQL_PASSWORD:admin}

springdoc:
  swagger-ui:
    use-root-path: true
    enabled: true

server:
  port: ${SERVER_PORT:8000}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
