spring:
  application:
    name: currency-conversion-service

springdoc:
  swagger-ui:
    use-root-path: true
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}


server:
  port: 8100