spring:
  application:
    name: telegram-bot-service
  devtools:
    livereload:
      port: 35730

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

server:
  port: ${SERVER_PORT:8200}

bot:
  username: ${BOT_USERNAME:@TsavaphCurrencyHistoryBot}
  token: ${BOT_TOKEN:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}